spring:
  application:
    name: springdata
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/spring-data-study
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        event:
          merge:
            entity_copy_observer: allow
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080