spring:
  application:
    name: spring-data-lab
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/spring-data-demo
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
